export default [
  {
    srcImg: 'https://i.ytimg.com/vi/pRXaj015rFk/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDUR_ZCvDzQjFkmAIsqb_Q2Rc_vyw',
    timeCount: '11:48:35',
    channelImg: 'https://yt3.ggpht.com/FYrwOEIxs-5Da4lJAj5MiXAo73BITsv4dCN42DxiK8gUKbj2XSSaxANWg2t21mXOQbc6myBHVQ=s68-c-k-c0x00ffffff-no-rj',
    title: 'Music for when you are stressed 🍀 Chill lofi | Music to Relax, Drive, Study, Chill',
    channelName: 'Lofi Zone',
    views: '115K',
    released: 'Streamed 2 months',
  },
  {
    srcImg: 'https://i.ytimg.com/vi/lkIFF4maKMU/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCGA-7bmtqY8g2SKnS-RyGE7BYr-A',
    timeCount: '12:24',
    channelImg: 'https://yt3.ggpht.com/ytc/AMLnZu80d66aj0mK3KEyMfpdGFyrVWdV5tfezE17IwRkhw=s68-c-k-c0x00ffffff-no-rj',
    title: '100+ JavaScript Concepts you Need to Know',
    channelName: 'Fireship',
    views: '11K',
    released: 'Streamed 1 month',
  },
  {
    srcImg: 'https://i.ytimg.com/vi/-bo-evsffVU/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDPj74L9gsc1hVLWzxupPXDfU1u7g',
    timeCount: '11:51',
    channelImg: 'https://yt3.ggpht.com/ejTsECFUFrGzfbae21z5izNIUgspl8ZxOEcYXyFMZ-fuRcbkhlLKKW-cVXVTOU2UsRw81SjNA0s=s68-c-k-c0x00ffffff-no-rj',
    title: '2016 IPF World Championship - Taylor Atwood',
    channelName: 'Taylor Atwood',
    views: '21K',
    released: '6 years',
  },
  {
    srcImg: 'https://i.ytimg.com/vi/w4WN-kl7sEY/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBqpP1SznQsoi7-GmhPFwl_nHmh-g',
    timeCount: '3:12',
    channelImg: 'https://yt3.ggpht.com/T2_cwuFO1FXD50wKTx4iHvF-H-EB0My1W75BFtqr_vE5tLmH-FR0gwEStvne_99V7V3_8qpFg7s=s68-c-k-c0x00ffffff-no-rj',
    title: 'AVATAR 2 - FINAL TRAILER (2022) 20th Century Studios | Disney+',
    channelName: 'Screen Culture',
    views: '321K',
    released: '5 days',
  },
  {
    srcImg: 'https://i.ytimg.com/vi/w4WN-kl7sEY/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBqpP1SznQsoi7-GmhPFwl_nHmh-g',
    timeCount: '3:12',
    channelImg: 'https://yt3.ggpht.com/T2_cwuFO1FXD50wKTx4iHvF-H-EB0My1W75BFtqr_vE5tLmH-FR0gwEStvne_99V7V3_8qpFg7s=s68-c-k-c0x00ffffff-no-rj',
    title: 'AVATAR 2 - FINAL TRAILER (2022) 20th Century Studios | Disney+',
    channelName: 'Screen Culture',
    views: '321K',
    released: '5 days',
  },
  {
    srcImg: 'https://i.ytimg.com/vi/ZCBlIq9eZdo/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAoTHyRCBX5S0IwE476edl7sQaTLA',
    timeCount: '10:12',
    channelImg: 'https://yt3.ggpht.com/s9gf6Dvl6IJHapXoPNlBc-GUeVOQ_46DUsxsmV5f9rWB4UEcFYdeUoU-8ENzyZVwKXcuPZTJ=s68-c-k-c0x00ffffff-no-rj',
    title: 'Coding Bootcamps: Are They Worth It? Tech Elevator Review, Job Prospects, and Salary',
    channelName: 'The Ethical Technologist',
    views: '321K',
    released: '1 year',
  },
  {
    srcImg: 'https://i.ytimg.com/vi/ZCBlIq9eZdo/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAoTHyRCBX5S0IwE476edl7sQaTLA',
    timeCount: '10:12',
    channelImg: 'https://yt3.ggpht.com/s9gf6Dvl6IJHapXoPNlBc-GUeVOQ_46DUsxsmV5f9rWB4UEcFYdeUoU-8ENzyZVwKXcuPZTJ=s68-c-k-c0x00ffffff-no-rj',
    title: 'Coding Bootcamps: Are They Worth It? Tech Elevator Review, Job Prospects, and Salary',
    channelName: 'The Ethical Technologist',
    views: '321K',
    released: '1 year',
  },
  {
    srcImg: 'https://i.ytimg.com/vi/ZCBlIq9eZdo/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAoTHyRCBX5S0IwE476edl7sQaTLA',
    timeCount: '10:12',
    channelImg: 'https://yt3.ggpht.com/s9gf6Dvl6IJHapXoPNlBc-GUeVOQ_46DUsxsmV5f9rWB4UEcFYdeUoU-8ENzyZVwKXcuPZTJ=s68-c-k-c0x00ffffff-no-rj',
    title: 'Coding Bootcamps: Are They Worth It? Tech Elevator Review, Job Prospects, and Salary',
    channelName: 'The Ethical Technologist',
    views: '321K',
    released: '1 year',
  },
]